# Generated by Django 5.2.4 on 2025-07-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="SimpleBlog",
                        help_text="The name of your blog/site",
                        max_length=100,
                    ),
                ),
                (
                    "site_description",
                    models.TextField(
                        blank=True, help_text="Brief description of your site"
                    ),
                ),
                (
                    "site_tagline",
                    models.CharField(
                        blank=True,
                        help_text="A short tagline for your site",
                        max_length=200,
                    ),
                ),
                (
                    "site_icon",
                    models.ImageField(
                        blank=True,
                        help_text="Site favicon/icon (recommended: 32x32 or 64x64 pixels)",
                        null=True,
                        upload_to="site_icons/",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, help_text="Contact email address", max_length=254
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, help_text="Contact phone number", max_length=20
                    ),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, help_text="Twitter profile URL"),
                ),
                (
                    "facebook_url",
                    models.URLField(blank=True, help_text="Facebook page URL"),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, help_text="Instagram profile URL"),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, help_text="LinkedIn profile URL"),
                ),
                (
                    "github_url",
                    models.URLField(blank=True, help_text="GitHub profile URL"),
                ),
                (
                    "posts_per_page",
                    models.PositiveIntegerField(
                        default=10, help_text="Number of posts to show per page"
                    ),
                ),
                (
                    "my_posts_per_page",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Number of posts to show per page in My Posts",
                    ),
                ),
                (
                    "search_results_per_page",
                    models.PositiveIntegerField(
                        default=15, help_text="Number of search results per page"
                    ),
                ),
                (
                    "show_author_info",
                    models.BooleanField(
                        default=True, help_text="Show author information on posts"
                    ),
                ),
                (
                    "show_post_dates",
                    models.BooleanField(
                        default=True, help_text="Show post creation dates"
                    ),
                ),
                (
                    "show_categories",
                    models.BooleanField(
                        default=True, help_text="Show category information"
                    ),
                ),
                (
                    "show_mood_badges",
                    models.BooleanField(
                        default=True, help_text="Show mood badges on posts"
                    ),
                ),
                (
                    "show_priority_badges",
                    models.BooleanField(
                        default=True, help_text="Show priority badges on posts"
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("default", "Default Blue"),
                            ("green", "Forest Green"),
                            ("purple", "Royal Purple"),
                            ("orange", "Sunset Orange"),
                            ("red", "Crimson Red"),
                            ("teal", "Ocean Teal"),
                            ("dark", "Dark Mode"),
                            ("light", "Light Mode"),
                        ],
                        default="default",
                        help_text="Choose the color theme for your site",
                        max_length=20,
                    ),
                ),
                (
                    "copyright_text",
                    models.CharField(
                        default="© 2025 SimpleBlog. All rights reserved.",
                        help_text="Copyright declaration",
                        max_length=200,
                    ),
                ),
                (
                    "footer_text",
                    models.TextField(blank=True, help_text="Additional footer text"),
                ),
                (
                    "powered_by_text",
                    models.CharField(
                        default="Built with Django",
                        help_text="Text to show in footer",
                        max_length=100,
                    ),
                ),
                (
                    "meta_keywords",
                    models.TextField(
                        blank=True, help_text="Default meta keywords for SEO"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True, help_text="Default meta description for SEO"
                    ),
                ),
                (
                    "google_analytics_id",
                    models.CharField(
                        blank=True,
                        help_text="Google Analytics tracking ID",
                        max_length=50,
                    ),
                ),
                (
                    "enable_search",
                    models.BooleanField(
                        default=True, help_text="Enable search functionality"
                    ),
                ),
                (
                    "enable_categories",
                    models.BooleanField(
                        default=True, help_text="Enable category functionality"
                    ),
                ),
                (
                    "enable_file_uploads",
                    models.BooleanField(
                        default=True, help_text="Enable file upload functionality"
                    ),
                ),
                (
                    "enable_mood_tracking",
                    models.BooleanField(default=True, help_text="Enable mood tracking"),
                ),
                (
                    "enable_priority_tracking",
                    models.BooleanField(
                        default=True, help_text="Enable priority tracking"
                    ),
                ),
                (
                    "enable_pinning",
                    models.BooleanField(
                        default=True, help_text="Enable post pinning functionality"
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
