# Generated by Django 5.2.4 on 2025-07-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="allow_anonymous_comments",
            field=models.BooleanField(
                default=True, help_text="Allow anonymous users to post comments"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="enable_comment_replies",
            field=models.BooleanField(
                default=True, help_text="Allow users to reply to comments"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="enable_comments",
            field=models.BooleanField(
                default=True, help_text="Enable comment functionality"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="max_comment_length",
            field=models.PositiveIntegerField(
                default=1000, help_text="Maximum length for comments (characters)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="require_comment_approval",
            field=models.BooleanField(
                default=False, help_text="Require admin approval for new comments"
            ),
        ),
    ]
