# Generated by Django 5.2.4 on 2025-07-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0003_sitesettings_show_attached_files_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="powered_by_url",
            field=models.URLField(
                blank=True, help_text="URL for the powered by link (optional)"
            ),
        ),
    ]
