# Generated by Django 5.2.4 on 2025-07-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0004_sitesettings_powered_by_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="enable_image_compression",
            field=models.BooleanField(
                default=True, help_text="Enable automatic image compression"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="image_compression_limit_mb",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Compress images larger than this size (MB)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="image_compression_quality",
            field=models.PositiveIntegerField(
                default=85,
                help_text="Image compression quality (1-100, higher = better quality)",
            ),
        ),
    ]
