# Generated by Django 5.2.4 on 2025-07-24 14:01

import django.db.models.deletion
import entries.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("desc", models.CharField(blank=True, max_length=1024, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entry_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "unique_together": {("name", "author")},
            },
        ),
        migrations.CreateModel(
            name="FileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to=entries.models.file_upload_path)),
                ("original_filename", models.CharField(max_length=255)),
                ("file_type", models.CharField(blank=True, max_length=50)),
                ("file_size", models.IntegerField(default=0)),
                ("is_image_file", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.CharField(blank=True, max_length=500)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("published_on", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "mood",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("happy", "Happy"),
                            ("sad", "Sad"),
                            ("excited", "Excited"),
                            ("calm", "Calm"),
                            ("anxious", "Anxious"),
                            ("neutral", "Neutral"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("private", "Private"), ("public", "Public")],
                        default="private",
                        max_length=10,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("is_pinned", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entries",
                        to="entries.category",
                    ),
                ),
                (
                    "files",
                    models.ManyToManyField(
                        blank=True, related_name="entries", to="entries.filemodel"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Entries",
                "ordering": ["-is_pinned", "-updated_on"],
                "indexes": [
                    models.Index(
                        fields=["author", "-updated_on"],
                        name="entries_ent_author__0b7059_idx",
                    ),
                    models.Index(
                        fields=["date", "-created_on"],
                        name="entries_ent_date_d4486e_idx",
                    ),
                    models.Index(
                        fields=["category", "-updated_on"],
                        name="entries_ent_categor_e1e75b_idx",
                    ),
                ],
            },
        ),
    ]
