# Generated by Django 5.2.4 on 2025-07-25 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_name", models.CharField(blank=True, max_length=100)),
                ("author_email", models.EmailField(blank=True, max_length=254)),
                ("content", models.TextField()),
                ("is_approved", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="entries.entry",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="entries.comment",
                    ),
                ),
            ],
            options={
                "ordering": ["created_on"],
                "indexes": [
                    models.Index(
                        fields=["entry", "created_on"],
                        name="entries_com_entry_i_38b1dd_idx",
                    ),
                    models.Index(
                        fields=["is_approved", "created_on"],
                        name="entries_com_is_appr_1a02d4_idx",
                    ),
                ],
            },
        ),
    ]
