# Generated by Django 5.2.4 on 2025-08-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of views for public posts'),
        ),
    ]
